FROM infiniflow/ragflow:v0.23.1

COPY docker/nginx/ragflow.conf /etc/nginx/conf.d/ragflow.conf
COPY docker/nginx/proxy.conf /etc/nginx/proxy.conf
COPY docker/nginx/nginx.conf /etc/nginx/nginx.conf

RUN sed -i 's|raise Exception("Embedding extraction from file path is not supported.")|embeds = []|g' \
    /ragflow/rag/app/naive.py

EXPOSE 80 9380
