FROM infiniflow/ragflow:v0.23.1

# Bake les configs nginx dans l'image
COPY docker/nginx/ragflow.conf /etc/nginx/conf.d/ragflow.conf
COPY docker/nginx/proxy.conf /etc/nginx/proxy.conf
COPY docker/nginx/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80 9380
